import config from "../../config";
import { ADVANCE } from "../../constants/constants";
import { INFO_LINK } from "../../constants/page-constant";

const avalancheMainnet = [
    {
        id: "daoAXA",
        name: "USDT/USDC/DAI",
        symbol: "USDT",
        symbols: ["USDT", "USDC", "DAI"],
        description: "Stablecoins",
        vaultSymbol: "daoAXA",
        erc20addresses: [
            "0xc7198437980c041c805A1EDcbA50c1Ce5db95118", 
            "0xA7D7079b0FEaD91F3e65f86E8915Cb59c1a4C664",
            "0xd586E7F844cEa2F87f50152665BCbc2C279D8d70",
        ],
        erc20address: "0xc7198437980c041c805A1EDcbA50c1Ce5db95118", 
        vaultContractAddress: "0xa4DCbe792f51E13Fc0E6961BBEc436a881e73194",
        vaultContractABI: config.avaxVaultContractABI,
        balance: 0, // Stores balance of selectedERC20Address
        balances: [0, 0, 0],
        vaultBalance: 0,
        decimals: 18,
        feeDecimals: 18,
        deposit: true,
        depositAll: true,
        withdraw: true,
        withdrawAll: true, 
        lastMeasurement: 6303210, 
        measurement: 1e18,
        price_id: ["tether", "usd-coin", "dai"],
        priceInUSD: [0, 0, 0],
        strategyName: "DAO AVAX DEX indexfarm: USDT USDC DAI",
        strategy: "DAO AVAX DEX indexfarm",
        strategyAddress: "0xde5d4923e7db1242a26693aa04fa0c0fcf7d11f4", 
        strategyContractABI: config.avaxStrategyContractABI,
        strategyInfo: "Yield farm with top Avalanche decentralised exchange tokens.",
        strategyDescription: "Invest in the top three Avalanche DEXs (Trader Joe, Pangolin Exchange and Lydia Finance) which will be paired with AVAX for additional yield farming.",
        historicalPriceId: "daoAXA_price",
        logoFormat: "png",
        risk: ADVANCE,
        strategyType: "daoAXA",
        cTokenAddress: "",
        cAbi: "",
        group: ADVANCE,
        tvlKey: "daoAXA_tvl",
        infoLink: INFO_LINK.DAODEGEN,
        isPopularItem: false,
        // isHappyHour: true, // use to render happy hour icon, note current logic uses a blanket HappyHour
    },
    {
        id: "daoAXS",
        name: "USDT/USDC/DAI",
        symbol: "USDT",
        symbols: ["USDT", "USDC", "DAI"],
        description: "Stablecoins",
        vaultSymbol: "daoAXS",
        erc20addresses: [
            "0xc7198437980c041c805A1EDcbA50c1Ce5db95118", 
            "0xA7D7079b0FEaD91F3e65f86E8915Cb59c1a4C664",
            "0xd586E7F844cEa2F87f50152665BCbc2C279D8d70",
        ],
        erc20address: "0xc7198437980c041c805A1EDcbA50c1Ce5db95118",  
        vaultContractAddress: "0x6fD8c0c6caFB7B99c47BbE332cAE42b32017CD58", 
        vaultContractABI: config.avaxStableVaultContractABI,
        balance: 0, // Stores balance of selectedERC20Address
        balances: [0, 0, 0],
        vaultBalance: 0,
        decimals: 18,
        feeDecimals: 18,
        deposit: true,
        depositAll: true,
        withdraw: true,
        withdrawAll: true, 
        lastMeasurement: 6473117, 
        measurement: 1e18,
        price_id: ["tether", "usd-coin", "dai"],
        priceInUSD: [0, 0, 0],
        strategyName: "DAO AVAX DEX-Stablecoin indexfarm: USDT USDC DAI",
        strategy: "DAO AVAX DEX-Stablecoin indexfarm",
        strategyAddress: "0xb309805d4de558042b537d7cc35e06ae5601e3af", 
        strategyContractABI: config.axsStrategyContractABI,
        strategyInfo: "Pairing top Avalanche decentralised exchange tokens with stablecoin for reduced volatility.",
        strategyDescription: "Pairing stablecoins with Avalanche DEX tokens (Trader Joe, Pangolin Exchange and Lydia Finance) to reduce volatility while still enjoying incentivised yield farming rewards.",
        historicalPriceId: "daoAXS_price",
        logoFormat: "svg",
        risk: ADVANCE,
        strategyType: "daoAXS",
        cTokenAddress: "",
        cAbi: "",
        group: ADVANCE,
        tvlKey: "daoAXS_tvl",
        infoLink: INFO_LINK.DAODEGEN,
        isPopularItem: false,
        // isHappyHour: true, // use to render happy hour icon, note current logic uses a blanket HappyHour
    },
    {
        id: "daoASA",
        name: "USDT/USDC/DAI",
        symbol: "USDT",
        symbols: ["USDT", "USDC", "DAI"],
        description: "Stablecoins",
        vaultSymbol: "daoASA",
        erc20addresses: [
            "0xc7198437980c041c805A1EDcbA50c1Ce5db95118", 
            "0xA7D7079b0FEaD91F3e65f86E8915Cb59c1a4C664",
            "0xd586E7F844cEa2F87f50152665BCbc2C279D8d70",
        ],
        erc20address: "0xc7198437980c041c805A1EDcbA50c1Ce5db95118",  
        vaultContractAddress: "0x8b8d29166729b31b482df6055EaDdcB944d4A1D8", 
        vaultContractABI: config.avaxStableVaultContractABI,
        balance: 0, // Stores balance of selectedERC20Address
        balances: [0, 0, 0],
        vaultBalance: 0,
        decimals: 18,
        feeDecimals: 18,
        deposit: true,
        depositAll: true,
        withdraw: true,
        withdrawAll: true,  
        lastMeasurement: 6473927, 
        measurement: 1e18,
        price_id: ["tether", "usd-coin", "dai"],
        priceInUSD: [0, 0, 0],
        strategyName: "DAO AVAX farm: USDT USDC DAI",
        strategy: "DAO AVAX farm",
        strategyAddress: "0x1ba17991cd6caf9133b8aae25cddd0e58f63fac3", 
        strategyContractABI: config.asaStrategyContractABI,
        strategyInfo: "Invest in the Avalanche chain with lowered volatility and additional yield farming.",
        strategyDescription: "Pure AVAX-stablecoin yield farming on DEXs to ride the growth of the Avalanche ecosystem.",
        historicalPriceId: "daoASA_price",
        logoFormat: "svg",
        risk: ADVANCE,
        strategyType: "daoASA",
        cTokenAddress: "",
        cAbi: "",
        group: ADVANCE,
        tvlKey: "daoASA_tvl",
        infoLink: INFO_LINK.DAODEGEN,
        isPopularItem: false,
        // isHappyHour: true, // use to render happy hour icon, note current logic uses a blanket HappyHour
    },
    {
        id: "daoA2S",
        name: "USDT/USDC/DAI",
        symbol: "USDT",
        symbols: ["USDT", "USDC", "DAI"],
        description: "Stablecoins",
        vaultSymbol: "daoA2S",
        erc20addresses: [
            "0xc7198437980c041c805A1EDcbA50c1Ce5db95118", 
            "0xA7D7079b0FEaD91F3e65f86E8915Cb59c1a4C664",
            "0xd586E7F844cEa2F87f50152665BCbc2C279D8d70",
        ],
        erc20address: "0xc7198437980c041c805A1EDcbA50c1Ce5db95118",
        vaultContractAddress: "0xA236FA927DC61d9566fAf62b29d287405c5e49fc", 
        vaultContractABI: config.avaxStableVaultContractABI,
        balance: 0, // Stores balance of selectedERC20Address
        balances: [0, 0, 0],
        vaultBalance: 0,
        decimals: 18,
        feeDecimals: 18,
        deposit: true,
        depositAll: true,
        withdraw: true,
        withdrawAll: true, 
        lastMeasurement: 6474452,
        measurement: 1e18,
        price_id: ["tether", "usd-coin", "dai"],
        priceInUSD: [0, 0, 0],
        strategyName: "DAO AVAX Stablecoin Farm: USDT USDC DAI",
        strategy: "DAO AVAX Stablecoin Farm",
        strategyAddress: "0x8b5b615556f34cf50112b15445db1a54bd671cca", 
        strategyContractABI: config.a2sStrategyContractABI,
        strategyInfo: "Minimise risks by farming pure stablecoin pairs on Avalanche.",
        strategyDescription: "Leverages many of the yield farming incentives provided on the Avalanche ecosystem while minimising the volatility risks with pure stablecoin-stablecoin pairs.",
        historicalPriceId: "daoA2S_price",
        logoFormat: "svg",
        risk: ADVANCE,
        strategyType: "daoA2S",
        cTokenAddress: "",
        cAbi: "",
        group: ADVANCE,
        tvlKey: "daoA2S_tvl",
        infoLink: INFO_LINK.DAODEGEN,
        isPopularItem: false,
        // isHappyHour: true, // use to render happy hour icon, note current logic uses a blanket HappyHour
    },
];

export default avalancheMainnet;