export const ERROR = "ERROR";
export const RESET_PROFILE = "RESET_PROFILE";

// #Accounts
export const CONNECTION_CONNECTED = "CONNECTION_CONNECTED";
export const CONNECTION_DISCONNECTED = "CONNECTION_DISCONNECTED";

export const GET_BALANCES = "GET_BALANCES";
export const BALANCES_RETURNED = "BALANCES_RETURNED";

export const GET_BALANCES_LIGHT = "GET_BALANCES_LIGHT";
export const BALANCES_LIGHT_RETURNED = "BALANCES_LIGHT_RETURNED";

export const GET_VAULT_BALANCES = "GET_VAULT_BALANCES";
export const VAULT_BALANCES_RETURNED = "VAULT_BALANCES_RETURNED";

// #Dashboard
export const GET_DASHBOARD_SNAPSHOT = "GET_DASHBOARD_SNAPSHOT";
export const DASHBOARD_SNAPSHOT_RETURNED = "DASHBOARD_SNAPSHOT_RETURNED";

export const GET_USD_PRICE = "GET_USD_PRICE";
export const USD_PRICE_RETURNED = "USD_PRICE_RETURNED";

// #Earn
export const INVEST = "INVEST";
export const INVEST_RETURNED = "INVEST_RETURNED";

export const INVEST_ALL = "INVEST_ALL";
export const INVEST_ALL_RETURNED = "INVEST_ALL_RETURNED";

export const REDEEM = "REDEEM";
export const REDEEM_RETURNED = "REDEEM_RETURNED";

// #Vaults
export const DEPOSIT_CONTRACT = "DEPOSIT_CONTRACT";
export const DEPOSIT_CONTRACT_RETURNED = "DEPOSIT_CONTRACT_RETURNED";
export const DEPOSIT_CONTRACT_RETURNED_COMPLETED =
  "DEPOSIT_CONTRACT_RETURNED_COMPLETED";

export const DEPOSIT_ALL_CONTRACT = "DEPOSIT_ALL_CONTRACT";
export const DEPOSIT_ALL_CONTRACT_RETURNED = "DEPOSIT_ALL_CONTRACT_RETURNED";
export const DEPOSIT_ALL_CONTRACT_RETURNED_COMPLETED =
  "DEPOSIT_ALL_CONTRACT_RETURNED_COMPLETED";

export const WITHDRAW_VAULT = "WITHDRAW_VAULT";
export const WITHDRAW_VAULT_RETURNED = "WITHDRAW_VAULT_RETURNED";
export const WITHDRAW_VAULT_RETURNED_COMPLETED =
  "WITHDRAW_VAULT_RETURNED_COMPLETED";

export const WITHDRAW_BOTH = "WITHDRAW_BOTH";

export const WITHDRAW_BOTH_VAULT = "WITHDRAW_BOTH_VAULT";
export const WITHDRAW_BOTH_VAULT_RETURNED = "WITHDRAW_BOTH_VAULT_RETURNED";
export const WITHDRAW_BOTH_VAULT_RETURNED_COMPLETED =
  "WITHDRAW_BOTH_VAULT_RETURNED_COMPLETED";
export const WITHDRAW_BOTH_VAULT_FAIL_RETURNED =
  "WITHDRAW_BOTH_VAULT_FAIL_RETURNED";

export const APPROVE_TRANSACTING = "APPROVE_TRANSACTING";
export const APPROVE_COMPLETED = "APPROVE_COMPLETED";

// #Zap
export const ZAP = "ZAP";
export const ZAP_RETURNED = "ZAP_RETURNED";

export const SWAP = "SWAP";
export const SWAP_RETURNED = "SWAP_RETURNED";

export const TRADE = "TRADE";
export const TRADE_RETURNED = "TRADE_RETURNED";

export const GET_CURV_BALANCE = "GET_CURV_BALANCE";
export const GET_CURV_BALANCE_RETURNED = "GET_CURV_BALANCE_RETURNED";

export const GET_BEST_PRICE = "GET_BEST_PRICE";
export const GET_BEST_PRICE_RETURNED = "GET_BEST_PRICE_RETURNED";

// #APR
export const GET_AGGREGATED_YIELD = "GET_AGGREGATED_YIELD";
export const GET_AGGREGATED_YIELD_RETURNED = "GET_AGGREGATED_YIELD_RETURNED";

// #Manage
export const DONATE = "DONATE";
export const DONATE_RETURNED = "DONATE_RETURNED";

export const REBALANCE = "REBALANCE";
export const REBALANCE_RETURNED = "REBALANCE_RETURNED";

export const GET_CONTRACT_EVENTS = "GET_CONTRACT_EVENTS";
export const GET_CONTRACT_EVENTS_RETURNED = "GET_CONTRACT_EVENTS_RETURNED";

export const IDAI = "IDAI";
export const IDAI_RETURNED = "IDAI_RETURNED";

export const GET_STATISTICS = "GET_STATISTICS";
export const STATISTICS_RETURNED = "STATISTICS_RETURNED";

export const GET_VAULT_BALANCES_FULL = "GET_VAULT_BALANCES_FULL";
export const VAULT_BALANCES_FULL_RETURNED = "VAULT_BALANCES_FULL_RETURNED";

export const TOGGLE_DRAWER = "TOGGLE_DRAWER";
export const DRAWER_RETURNED = "DRAWER_RETURNED";

export const GET_STRATEGY_BALANCES_FULL = "GET_STRATEGY_BALANCES_FULL";
export const STRATEGY_BALANCES_FULL_RETURNED =
  "STRATEGY_BALANCES_FULL_RETURNED";

// #global (新增)
export const TOGGLE_THEME = "TOGGLE_THEME"; // 切换主题
export const CURRENT_THEME_RETURNED = "CURRENT_THEME_RETURNED"; // 返回当前主题
export const CHANGE_NETWORK = "CHANGE_NETWORK"; // 设置当前网络

// 获取接口信息
export const GET_VAULT_INFO = "GET_VAULT_INFO";

// Strategy Risk Level
export const BASIC = "Basic";
export const ADVANCE = "Advance";
export const EXPERT = "Expert";
export const DEGEN = "Degen";
export const ALL = "All";

// Biconomy
export const BICONOMY_CONNECTED = "BICONOMY_CONNECTED";

export const GET_HAPPY_HOUR_STATUS = "GET_HAPPY_HOUR_STATUS";
export const HAPPY_HOUR_VERIFY = "HAPPY_HOUR_VERIFY";
export const HAPPY_HOUR_RETURN = "HAPPY_HOUR_RETURN";
export const DEPOSIT_CONTRACT_HAPPY_HOUR_RETURNED_COMPLETED =
  "DEPOSIT_CONTRACT_HAPPY_HOUR_RETURNED_COMPLETED";

// Block Explorers
export const BLOCK_EXPLORERS = {
  1: "https://etherscan.io/tx/",
  42: "https://kovan.etherscan.io/tx/",
  56: "https://bscscan.com/tx/",
  97: "https://testnet.bscscan.com/tx/",
};

// Pools
export const FIND_DAOMINE_POOL = "FIND_DAOMINE_POOL";
export const DAOMINE_POOL_RETURNED = "DAOMINE_POOL_RETURNED";
export const DEPOSIT_DAOMINE = "DEPOSIT_DAOMINE";
export const DEPOSIT_DAOMINE_RETURNED = "DEPOSIT_DAOMINE_RETURNED";
export const DEPOSIT_DAOMINE_RETURNED_COMPLETED =
  "DEPOSIT_DAOMINE_RETURNED_COMPLETED";
export const WITHDRAW_DAOMINE = "WITHDRAW_DAOMINE";
export const WITHDRAW_DAOMINE_RETURNED = "WITHDRAW_DAOMINE_RETURNED";
export const WITHDRAW_DAOMINE_RETURNED_COMPLETED =
  "WITHDRAW_DAOMINE_RETURNED_COMPLETED";

// 获取DVG信息
export const GET_DVG_INFO = "GET_DVG_INFO";
// 获取DVG成功
export const GET_DVG_BALANCE_SUCCESS = "GET_DVG_BALANCE_SUCCESS";
// 充值XDVG
export const DEPOSIT_XDVG = "DEPOSIT_XDVG";
//获取xdvg
export const GET_XDVG_BALANCE = "GET_XDVG_BALANCE";
//获取xdvg可用成功
export const GET_XDVG_BALANCE_SUCCESS = "GET_XDVG_BALANCE_SUCCESS";
//取消质押中的DVG
export const WIDTHDRAW_XDVG = "WIDTHDRAW_XDVG";
//获取DVG APR
export const GET_DVG_APR = "GET_DVG_APR";
//获取DVG APR 成功
export const GET_XDVG_APR_SUCCESS = "GET_XDVG_APR_SUCCESS";
//充值DVG成功
export const DEPOSIT_DVG_RETURNED = "DEPOSIT_DVG_RETURNED";
//提现DVG成功
export const WITHDRAW_DVG_RETURNED = "WITHDRAW_DVG_RETURNED";

export const NETWORK = {
  ETHEREUM: 1,
  KOVAN: 42,
  MATIC: 137,
  MUMBAI: 80001,
}
